### ISSUE TITLE
根目录中的cedict_ts文件

### ISSUE THREAD

**Issue by liang0802** [cumany/Blue-topaz-examples#41]
请问大大，根目录中的cedict_ts文件的作用是什么？能移动到其他位置吗？可以删除吗？

**Comment by cumany** [comment]
obsidian-various-complements-plugin 需要这个文件，作用是对中文进行分词，方便自动补全操作。如果不需要这个插件文件是可以删除的。如果需要这个插件又觉得这个文件碍事可以通过以下css代码隐藏
```css
.nav-file-title.is-unsupported[data-path="cedict_ts.u8"]
{
  display: none;
}
```
