### ISSUE TITLE
有办法让使滚动条只能滚动到最后一行吗？

### ISSUE THREAD

**Issue by pincman** [cumany/Blue-topaz-examples#7]
使用了这个库一段时间，目前发觉有个问题是主页拖动滚动条是跟obsidian默认的一行底部会有一大堆空白，能不能类似vscode的`editor.scrollBeyondLastLine`一样设置为只能滚动到最后一行呢？

**Comment by cumany** [comment]
当然可以
后面我会对myhome样式添加这个功能。当然你也可以自己动手添加，如果你的主页跟我示例库一样就在myhome样式片段里添加这一句
```css
 .myhome.markdown-preview-view .markdown-preview-section
  {
    padding-bottom: 0px !important;
  }
```
